[package]
name = "inxanelang"
version = "0.1.0"
authors = ["inxaneninja <inxaneninja@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.1.4"